services:
  spring_service:
    build: .
    restart: always
    ports:
      - 8080:8080
    networks:
      - spring-network
    environment:
      - "spring_active_profile=dev"
      - "db_url=jdbc:mysql://db:3306/turkdil?allowPublicKeyRetrieval=true"
      - "db_username=mysqluser"
      - "db_password=mysqlpassword"
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - .m2:/root/.m2

  db:
    container_name: db
    image: "mysql:8.0"
    restart: always
    ports:
      - 3306:3306
    networks:
      - spring-network
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 2s
      timeout: 20s
      retries: 10
    environment:
      MYSQL_DATABASE: turkdil
      MYSQL_USER: mysqluser
      MYSQL_PASSWORD: mysqlpassword
      MYSQL_ROOT_PASSWORD: mysqlpassword

  frontend-prod:
    build:
      context: ./../frontend
    container_name: nuxt-app
    restart: always
    ports:
      - "3000:3000"
      - "3001:3001"
      - "24678:24678"
    depends_on:
      - spring_service
networks:
  spring-network: